/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarBottomNavigation: typeof import('@varlet/ui')['_BottomNavigationComponent']
    VarBottomNavigationItem: typeof import('@varlet/ui')['_BottomNavigationItemComponent']
    VarBtn: typeof import('@varlet/ui')['_BtnComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarChip: typeof import('@varlet/ui')['_ChipComponent']
    VarDatePicker: typeof import('@varlet/ui')['_DatePickerComponent']
    VarDatetimePicker: typeof import('@varlet/ui')['_DatetimePickerComponent']
    VarDateTimePicker: typeof import('@varlet/ui')['_DateTimePickerComponent']
    VarDialog: typeof import('@varlet/ui')['_DialogComponent']
    VarForm: typeof import('@varlet/ui')['_FormComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarList: typeof import('@varlet/ui')['_ListComponent']
    VarLoading: typeof import('@varlet/ui')['_LoadingComponent']
    VarMenu: typeof import('@varlet/ui')['_MenuComponent']
    VarOption: typeof import('@varlet/ui')['_OptionComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
    VarPullRefresh: typeof import('@varlet/ui')['_PullRefreshComponent']
    VarSelect: typeof import('@varlet/ui')['_SelectComponent']
    VarSkeleton: typeof import('@varlet/ui')['_SkeletonComponent']
    VarSnackbar: typeof import('@varlet/ui')['_SnackbarComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarSwipe: typeof import('@varlet/ui')['_SwipeComponent']
    VarSwipeItem: typeof import('@varlet/ui')['_SwipeItemComponent']
    VarTab: typeof import('@varlet/ui')['_TabComponent']
    VarTabItem: typeof import('@varlet/ui')['_TabItemComponent']
    VarTabs: typeof import('@varlet/ui')['_TabsComponent']
    VarTabsItems: typeof import('@varlet/ui')['_TabsItemsComponent']
    VarUploader: typeof import('@varlet/ui')['_UploaderComponent']
  }
  export interface ComponentCustomProperties {
    vLazy: typeof import('@varlet/ui')['_LazyComponent']
    vRipple: typeof import('@varlet/ui')['_RippleComponent']
  }
}
